In [1]:
import numpy as np

* Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))

In [2]:
n = int(input('Введите число '))
x = np.flipud(np.arange(0, n)) 
x

Введите число 11


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

* Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [3]:
y = np.diag(np.arange(n, -1, -1), k=0)
y

array([[11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [4]:
np.trace(y)

66

In [7]:
a = [[11,2,4],[4,5,6],[10,8,-1]] #вариант для другой матрицы без нулей 
b = np.asarray(a)
print('Diagonal (sum): ', np.trace(b))
print('Diagonal (elements): ', np.diagonal(b))

Diagonal (sum):  15
Diagonal (elements):  [11  5 -1]


* Решите систему уравнений:
* 4x + 2y + z = 4
* x + 3y = 12
* 5y + 4z = -3

In [8]:
from numpy import linalg

In [9]:
s = np.array( [ [4, 2, 1], [1, 3, 0], [0, 5, 4] ] )

In [10]:
t = b = np.array( [4, 12, -3] )

In [11]:
linalg.solve(s, t)

array([ 0.46666667,  3.84444444, -5.55555556])

* Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [12]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [13]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [14]:
i=0
for i in users_stats:
    aLength = np.sqrt( (users_stats[i]*users_stats[i]).sum() )
    bLength = np.sqrt( (next_user_stats*next_user_stats).sum() )
    print(np.dot( users_stats, next_user_stats ) / ( aLength * bLength ))
    i +=1

[0.07905694 0.39528471 0.15811388 0.39528471 0.15811388 0.
 0.         0.23717082 0.         0.        ]
[0.23094011 0.28867513 0.11547005 0.28867513 0.11547005 0.
 0.         0.17320508 0.         0.        ]
[0.18257419 0.36514837 0.09128709 0.22821773 0.09128709 0.
 0.         0.13693064 0.         0.        ]
[0.15936381 0.31872763 0.19920477 0.19920477 0.07968191 0.
 0.         0.11952286 0.         0.        ]
[0.17213259 0.34426519 0.21516574 0.34426519 0.0860663  0.
 0.         0.12909944 0.         0.        ]
[0.17056057 0.34112115 0.21320072 0.34112115 0.21320072 0.
 0.         0.12792043 0.         0.        ]
[0.17213259 0.34426519 0.21516574 0.34426519 0.21516574 0.12909944
 0.         0.12909944 0.         0.        ]
[0.16754156 0.33508313 0.20942695 0.33508313 0.20942695 0.12565617
 0.12565617 0.12565617 0.         0.        ]
[0.16129557 0.32259114 0.20161946 0.32259114 0.20161946 0.12097168
 0.12097168 0.24194335 0.         0.        ]
[0.16754156 0.33508313 0.209426